// Code generated by mockery. DO NOT EDIT.

package servermock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	metadata "google.golang.org/grpc/metadata"

	proto "github.com/grpc-mongo-go/gen/proto"
)

// ServerStreamMock is an autogenerated mock type for the BlogService_ListBlogsServer type
type ServerStreamMock struct {
	mock.Mock
}

type ServerStreamMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ServerStreamMock) EXPECT() *ServerStreamMock_Expecter {
	return &ServerStreamMock_Expecter{mock: &_m.Mock}
}

// Context provides a mock function with given fields:
func (_m *ServerStreamMock) Context() context.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// ServerStreamMock_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type ServerStreamMock_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *ServerStreamMock_Expecter) Context() *ServerStreamMock_Context_Call {
	return &ServerStreamMock_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *ServerStreamMock_Context_Call) Run(run func()) *ServerStreamMock_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ServerStreamMock_Context_Call) Return(_a0 context.Context) *ServerStreamMock_Context_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerStreamMock_Context_Call) RunAndReturn(run func() context.Context) *ServerStreamMock_Context_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function with given fields: m
func (_m *ServerStreamMock) RecvMsg(m interface{}) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerStreamMock_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type ServerStreamMock_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *ServerStreamMock_Expecter) RecvMsg(m interface{}) *ServerStreamMock_RecvMsg_Call {
	return &ServerStreamMock_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *ServerStreamMock_RecvMsg_Call) Run(run func(m interface{})) *ServerStreamMock_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *ServerStreamMock_RecvMsg_Call) Return(_a0 error) *ServerStreamMock_RecvMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerStreamMock_RecvMsg_Call) RunAndReturn(run func(interface{}) error) *ServerStreamMock_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: _a0
func (_m *ServerStreamMock) Send(_a0 *proto.Blog) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*proto.Blog) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerStreamMock_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type ServerStreamMock_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - _a0 *proto.Blog
func (_e *ServerStreamMock_Expecter) Send(_a0 interface{}) *ServerStreamMock_Send_Call {
	return &ServerStreamMock_Send_Call{Call: _e.mock.On("Send", _a0)}
}

func (_c *ServerStreamMock_Send_Call) Run(run func(_a0 *proto.Blog)) *ServerStreamMock_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*proto.Blog))
	})
	return _c
}

func (_c *ServerStreamMock_Send_Call) Return(_a0 error) *ServerStreamMock_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerStreamMock_Send_Call) RunAndReturn(run func(*proto.Blog) error) *ServerStreamMock_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendHeader provides a mock function with given fields: _a0
func (_m *ServerStreamMock) SendHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SendHeader")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerStreamMock_SendHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendHeader'
type ServerStreamMock_SendHeader_Call struct {
	*mock.Call
}

// SendHeader is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *ServerStreamMock_Expecter) SendHeader(_a0 interface{}) *ServerStreamMock_SendHeader_Call {
	return &ServerStreamMock_SendHeader_Call{Call: _e.mock.On("SendHeader", _a0)}
}

func (_c *ServerStreamMock_SendHeader_Call) Run(run func(_a0 metadata.MD)) *ServerStreamMock_SendHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *ServerStreamMock_SendHeader_Call) Return(_a0 error) *ServerStreamMock_SendHeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerStreamMock_SendHeader_Call) RunAndReturn(run func(metadata.MD) error) *ServerStreamMock_SendHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function with given fields: m
func (_m *ServerStreamMock) SendMsg(m interface{}) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerStreamMock_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type ServerStreamMock_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *ServerStreamMock_Expecter) SendMsg(m interface{}) *ServerStreamMock_SendMsg_Call {
	return &ServerStreamMock_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *ServerStreamMock_SendMsg_Call) Run(run func(m interface{})) *ServerStreamMock_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *ServerStreamMock_SendMsg_Call) Return(_a0 error) *ServerStreamMock_SendMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerStreamMock_SendMsg_Call) RunAndReturn(run func(interface{}) error) *ServerStreamMock_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// SetHeader provides a mock function with given fields: _a0
func (_m *ServerStreamMock) SetHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SetHeader")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerStreamMock_SetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeader'
type ServerStreamMock_SetHeader_Call struct {
	*mock.Call
}

// SetHeader is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *ServerStreamMock_Expecter) SetHeader(_a0 interface{}) *ServerStreamMock_SetHeader_Call {
	return &ServerStreamMock_SetHeader_Call{Call: _e.mock.On("SetHeader", _a0)}
}

func (_c *ServerStreamMock_SetHeader_Call) Run(run func(_a0 metadata.MD)) *ServerStreamMock_SetHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *ServerStreamMock_SetHeader_Call) Return(_a0 error) *ServerStreamMock_SetHeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerStreamMock_SetHeader_Call) RunAndReturn(run func(metadata.MD) error) *ServerStreamMock_SetHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SetTrailer provides a mock function with given fields: _a0
func (_m *ServerStreamMock) SetTrailer(_a0 metadata.MD) {
	_m.Called(_a0)
}

// ServerStreamMock_SetTrailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTrailer'
type ServerStreamMock_SetTrailer_Call struct {
	*mock.Call
}

// SetTrailer is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *ServerStreamMock_Expecter) SetTrailer(_a0 interface{}) *ServerStreamMock_SetTrailer_Call {
	return &ServerStreamMock_SetTrailer_Call{Call: _e.mock.On("SetTrailer", _a0)}
}

func (_c *ServerStreamMock_SetTrailer_Call) Run(run func(_a0 metadata.MD)) *ServerStreamMock_SetTrailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *ServerStreamMock_SetTrailer_Call) Return() *ServerStreamMock_SetTrailer_Call {
	_c.Call.Return()
	return _c
}

func (_c *ServerStreamMock_SetTrailer_Call) RunAndReturn(run func(metadata.MD)) *ServerStreamMock_SetTrailer_Call {
	_c.Call.Return(run)
	return _c
}

// NewServerStreamMock creates a new instance of ServerStreamMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServerStreamMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServerStreamMock {
	mock := &ServerStreamMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
